### ISSUE TITLE
Самозагрузка

### ISSUE THREAD

**Issue by Alskator** [voxeltycoon/bug-tracker-ru#12]
![21](https://user-images.githubusercontent.com/52891333/61187113-79b88b80-a676-11e9-9dfe-2ef89f13768d.PNG)
![22](https://user-images.githubusercontent.com/52891333/61187114-7a512200-a676-11e9-847b-5c714d8f69f6.PNG)
![23](https://user-images.githubusercontent.com/52891333/61187115-7a512200-a676-11e9-808c-8eae2d414dbe.PNG)

Товар появляется сам собой в вагонах, из воздуха. Происходит при следующих действиях. Я назначаю на станцию погрузки где нет нужного груза (режим "полная загрузка"). После переназначаю на нужную станцию, где есть товар под эти вагоны. После этого поезд отправляется на новую станцию и начинает накапливать у себя нужный товар во время движения к нужной станции.

**Comment by Alskator** [comment]
![24](https://user-images.githubusercontent.com/52891333/61187180-46c2c780-a677-11e9-8db6-7f135b7ddca3.PNG)

**Comment by Alskator** [comment]
https://vk.com/video90396977_456239026

**Comment by MaximBarminov** [comment]
Исправлено в 0.74

**Comment by voxeltycoon** [comment]
Исправлено в 0.74
