### ISSUE TITLE
Нет перевода в меню производства.

### ISSUE THREAD

**Issue by Headmast** [voxeltycoon/bug-tracker-ru#18]
**Описание**
Английский текст "Pick recipe" в русской версии игры
<img width="461" alt="Screenshot 2019-07-19 23 10 55" src="https://user-images.githubusercontent.com/8297666/61574326-eb556700-aac6-11e9-9e33-a051fd6c989f.png">

**Шаги для воспроизведения**
Нажать на любое производство для выбора производимой продукции.

**Версия игры**
0.74

**Платформа**
Mac OS Catalina beta 3

**Воспроизводимость**
Всегда

**Comment by TechTex** [comment]
Проблема так же воспроизводится на Windows версии (0.74 2019-07-19 ITCH_RU PRE-ALPHA)

**Comment by andrewpey** [comment]
Исправлено в `0.80.1`.
