### ISSUE TITLE
Надпись при зажатии shift в меню покупки транспорта не переведена

### ISSUE THREAD

**Issue by mayorandrew** [voxeltycoon/bug-tracker-ru#2]
**Описание**
В меню покупки транспорта при зажатии Shift выводится "Add many units while holding SHIFT" и "Release SHIFT to add units"

**Способы для воспроизведения**
Построить депо/гараж, открыть меню покупки, зажать Shift, навести указатель мыши на ТС.

**Версия игры**
v0.72 русская региональная

**Платформа**
Windows 10

**Повторяемость**
Всегда

**Comment by voxeltycoon** [comment]
Done in 0.73.
