### ISSUE TITLE
В окне покупки поезда не отображаются поезда, если у них сразу несколько типов

### ISSUE THREAD

**Issue by inf1nitev0id** [voxeltycoon/bug-tracker-ru#25]
**Описание**
Если отображать только тип "с двигателем", то локомотив E5K не отображается.
![изображение](https://user-images.githubusercontent.com/52628621/61594472-fad2ce00-abf4-11e9-907f-62e5367a1380.png)
Если же отображать только "наборы", то не отображается вообще ничего.
![изображение](https://user-images.githubusercontent.com/52628621/61594481-1ccc5080-abf5-11e9-89f9-42877ee128ce.png)
А вот если выбрать и "наборы", и "с двигателем" одновременно, то отображаются уже все локомотивы, включая E5K.
![изображение](https://user-images.githubusercontent.com/52628621/61594518-7d5b8d80-abf5-11e9-8123-0c82c9660c08.png)
В общем какая-то странная логика у фильтра

**Шаги для воспроизведения**
Понажимать на кнопки "тип" в фильтре окна покупки поезда.

**Версия игры**
0.74

**Платформа**
Windows 7 x64

**Воспроизводимость**
Постоянно

**Comment by andrewpey** [comment]
Исправлено в [0.81](https://voxeltycoon.xyz/changelog#0.81)
