### ISSUE TITLE
Нет перевода раздела браузер модов.

### ISSUE THREAD

**Issue by Headmast** [voxeltycoon/bug-tracker-ru#29]
**Описание**
Возможно этот раздел будет сильно модифицирован, но пока перевода нет.

<img width="1680" alt="Screenshot 2019-07-20 15 04 55" src="https://user-images.githubusercontent.com/8297666/61608799-c1ce4400-ac5c-11e9-81b0-1e290b284794.png">

**Шаги для воспроизведения**

**Версия игры**
0.74

**Платформа**
Mac OS Catalina beta 3

**Воспроизводимость**
Всегда

**Comment by andrewpey** [comment]
Раздел был сильно модифицирован и переведен в [0.83](https://voxeltycoon.xyz/changelog#0.83).
