### ISSUE TITLE
Произошла ошибка

### ISSUE THREAD

**Issue by mayorandrew** [voxeltycoon/bug-tracker-ru#31]
**Описание**
В правом-верхнем углу экрана появилась красная кнопка с жучком и фразой "Произошла ошибка", которая при нажатии показывает в экплорере файл Player.log (приложен)

Не уверен, что я сразу его заметил, поэтому не могу точно сказать, какие мои действия привели к ошибке.

Глобально в этот момент я перестраивал железнодорожную развязку на паузе. Потом снял паузу и через некоторое время заметил красную кнопку.

После сохранения/загрузки больше она не появлялась.

**Версия игры**
v0.74 Русская

**Платформа**
Windows 10 1809

**Воспроизводимость**
Пока один раз

**Player.log**
https://drive.google.com/file/d/146jCGuiWFOM6IPWa0J8zCYY9lJJ6Q2wu/view?usp=sharing

**Comment by andrewpey** [comment]
Подобная ошибка была исправлена в одной из предыдущих версий.
