### ISSUE TITLE
После аварии изменяется название грузовика

### ISSUE THREAD

**Issue by villario** [voxeltycoon/bug-tracker-ru#33]
**Описание**
*Данный баг был замечен во время воспроизведения бага #32*
После аварии название грузовика меняется с "**Автомобиль №**" на "**Train #**"

**Шаги для воспроизведения**
1. Проверить название автомобиля до аварии:
![название](https://user-images.githubusercontent.com/4144336/61937706-1bee4280-af98-11e9-8f01-a2fee0050889.jpg)
2. Спровоцировать аварию этого автомобиля (например, способом описанным в #32).
3. Проверить название автомобиля после аварии:
![смена_названия](https://user-images.githubusercontent.com/4144336/61937855-6d96cd00-af98-11e9-927b-41c4c8a534e7.jpg)

**Версия игры**
0.74 2019-07-19 ITCH_RU PRE-ALPHA

**Платформа**
Windows 10 1903

**Воспроизводимость**
Постоянно.

**Comment by andrewpey** [comment]
Исправлено в [0.83](https://voxeltycoon.xyz/changelog#0.83).
