### ISSUE TITLE
При перемещении автомобилей в гараж транспорт замирает на карте и выдаёт ошибку v075

### ISSUE THREAD

**Issue by iartsart** [voxeltycoon/bug-tracker-ru#37]
**Описание**
03/08 после обновления до вер 075 при перемещении в гараж автомобилей, все автомобили замирают на карте и больше не двигаются. Помогало сохранение - загрузка, но один раз (последний) даже после перезагрузки не помогло

**Шаги для воспроизведения**
При отправлении в гараж а/м происходит зависание транспорта

**Версия игры**
075

**Платформа**
Win 10 ЗPro

**Воспроизводимость**
3-4 раза за вечер.
[Player.log](https://github.com/voxeltycoon/bug-tracker-ru/files/3464273/Player.log)
![ошибка](https://user-images.githubusercontent.com/53663642/62416367-1650c680-b642-11e9-93c7-9e7f13ddfea3.JPG)

**Comment by andrewpey** [comment]
Исправлено в 0.77.
