### ISSUE TITLE
Баг с отправлением поезда в депо

### ISSUE THREAD

**Issue by Shawn0592** [voxeltycoon/bug-tracker-ru#38]
**Описание**
После отправки поезда в депо, я решил передумать и отменить данное действие. У меня ничего не вышло, и я решил попробовать пропустить текущее задание. В итоге всего этого безобразия у меня возникла ошибка.

**Шаги для воспроизведения**
_1._ Открыть меню управления поездом;
_2._ Поставить игру на паузу;
_3._ Отправить поезд в депо;
_4._ Пропустить текущее задание у поезда;
_5._ Выйти с режима паузы;

**Версия игры**
0.75

**Платформа**
Windows 10 Корпоративная LTSC: Версия 18069 _(Сборка ОС 17763.615)_

**Воспроизводимость**
Только при проделанных действиях

![image](https://user-images.githubusercontent.com/40145478/62688215-1568bd80-b9d1-11e9-9acc-2300ef0f6b78.png)
[Player.log](https://github.com/voxeltycoon/bug-tracker-ru/files/3480672/Player.log)

**Comment by andrewpey** [comment]
Исправлено в 0.76.
