### ISSUE TITLE
Исследования в модах

### ISSUE THREAD

**Issue by inf1nitev0id** [voxeltycoon/bug-tracker-ru#39]
**Описание**
Если установить мод, добавляющий исследования, а потом открыть мир с настройкой "всё исследовано", то исследования из мода не будут открыты, и их всё равно придётся исследовать. При создании мира с этой настройкой уже после установки мода такой проблемы не возникает.

**Шаги для воспроизведения**
Создать мир с настройкой исследований "всё исследовано". Установить мод, добавляющий исследования. Открыть созданный мир.

**Версия игры**
v0.75

**Платформа**
Windows 7 x64

**Воспроизводимость**
Постоянно

**Comment by andrewpey** [comment]
Такое поведение не является ошибкой. Подключение модов в уже созданные миры на данный момент не поддерживается игрой (хотя и было доступно до 0.77 версии).
