### ISSUE TITLE
Моддинг. Использование C# модов, изменяющих загруженные ресурсы игры.

### ISSUE THREAD

**Issue by meinroman** [voxeltycoon/bug-tracker-ru#42]
**Описание**
При обновлении через dll мода в VoxelTycoon.R каких-либо загружаемых данных, в частности VoxelTycoon.R.Curves.Rails, если после загрузки игры выйти в меню и выключить мод на старте новой игры, или загрузить сохранение с выключенным модом, то обновленные модификацией данные остаются измененными. Исправляется только перезапуском игры.

**Шаги для воспроизведения**
Использование модификаций, которые меняют выгружаемые через RHelper.Load ресурсы.

**Версия игры**
0.81.1

**Платформа**
Win 10

**Воспроизводимость**
Для данного случая всегда

**Comment by andrewpey** [comment]
Это не баг.

К сожалению, изменение оригиналов ресурсов не подразумевается именно по этой причине — любые изменения сохраняются до выхода из игры. Изменять надо их копии (ну или пытаться на выход в главное меню вернуть их в изначальное состояние).

Если без изменения оригиналов ресурсов реализовать мод не представляется возможным, значит это хороший кандидат для предложения новой функциональности, необходимой для конкретной задачи. Сделать это можно здесь: https://github.com/voxeltycoon/suggestions-ru).
