### ISSUE TITLE
При публикации мода "что-то идёт не так"

### ISSUE THREAD

**Issue by inf1nitev0id** [voxeltycoon/bug-tracker-ru#51]
**Описание**
При публикации мода в мод-браузере сначала всё идёт как нужно, но когда полоса загрузки заполняется, появляется вот эта ошибка:
![изображение](https://user-images.githubusercontent.com/52628621/84601518-5f3ff100-ae89-11ea-801b-cb1cbfa40652.png)
При этом мод появляется в браузере (и в дискорде появляются новости об этом, а если нажать на публикацию несколько раз, то и новостей появится несколько), т.е. загрузка мода происходит успешно. А вот клиент после этого не записывает мод в файл identity.json, из-за чего игра не считает мод опубликованным мной и функции обновления мода не доступны, только публикация. Пока что справляюсь с этим обновлением этого файла вручную.
Я жаловался на это ещё в момент загрузки своего первого мода, и с тех пор ничего не изменилось, разве что кажется, что раньше была ошибка 500, а сейчас просто что-то идёт не так.
А ещё сейчас существует возможность установить мод, который ты сам же и опубликовал, вот это уже только с переделкой мод-браузера появилось.
![изображение](https://user-images.githubusercontent.com/52628621/84601767-4c2e2080-ae8b-11ea-8e1c-b1a3d8ff4c93.png)
При нажатии на "установить" появляется вот эта ошибка:
![Скриншот 14-06-2020 220442](https://user-images.githubusercontent.com/52628621/84601774-56501f00-ae8b-11ea-8cea-186b6e2b60e3.png)
Т.е. игра не может установить мод, потому что такая папка уже существует, а не потому что "ты чо дурак, это ж твой мод".

**Шаги для воспроизведения**
Опубликовать мод в браузере модов.

**Версия игры**
0.84.1.132359349156935096 itch_ru

**Платформа**
Windows 7 x64

**Воспроизводимость**
Постоянно

**Comment by inf1nitev0id** [comment]
Оказывается я уже писал об этом сюда почти год назад (я думал, что только в дискорде писал). #11  
Но тогда не было кнопки установки, когда мод считался своим, да и технически сообщение об ошибке изменилось, так что будем считать, что это другой баг.

**Comment by andrewpey** [comment]
Спасибо, посмотрим.

**Comment by andrewpey** [comment]
Исправлено на сервере.
